# Generated by Django 5.2.4 on 2025-07-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.topup')),
            ],
        ),
    ]
